extends:
  - './node_modules/gts'

rules:
  "@typescript-eslint/no-empty-interface": 'off'
  "@typescript-eslint/no-unused-vars":
    - warn
    - argsIgnorePattern: "^_"
  "node/no-unpublished-import":
    - 'off'
    - allowModules: ["ava", "graphology-types"]
