{{- if and (.Values.service.enabled) (eq .Values.application.track "stable") (or (.Values.ingress.enabled) (not (hasKey .Values.ingress "enabled"))) -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}-external
  labels:
    app: {{ template "appname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version| replace "+" "_" }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
{{- if .Values.ingress.annotations_external }}
{{ toYaml .Values.ingress.annotations_external | indent 4 }}
{{- end }}
{{- with .Values.ingress.modSecurity }}
{{- if .enabled }}
    nginx.ingress.kubernetes.io/modsecurity-transaction-id: "$server_name-$request_id"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine {{ .secRuleEngine | default "DetectionOnly" | title }}
{{- range $rule := .secRules }}
{{ (include "secrule" $rule) | indent 6 }}
{{- end }}
{{- end }}
{{- end }}
{{- if .Values.prometheus.metrics }}
    nginx.ingress.kubernetes.io/server-snippet: |-
      location /metrics {
          deny all;
      }

{{- end }}
spec:
{{- if .Values.ingress.tls_external.enabled }}
  tls:
  - hosts:
{{- if .Values.service.commonName_external }}
    - {{ template "hostname" .Values.service.commonName_external }}
{{- end }}
    - {{ template "hostname" .Values.service.url_external }}
{{- if .Values.service.additionalHosts_external }}
{{- range $host := .Values.service.additionalHosts_external }}
    - {{ $host }}
{{- end -}}
{{- end }}
    secretName: {{ .Values.ingress.tls_external.secretName | default (printf "%s-tls" (include "fullname" .)) }}
{{- end }}
  rules:
  - host: {{ template "hostname" .Values.service.url_external }}
    http:
      &httpRule
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ template "fullname" . }}
            port:
              number: {{ .Values.service.externalPort }}
{{- if .Values.service.commonName_external }}
  - host: {{ template "hostname" .Values.service.commonName_external }}
    http:
      <<: *httpRule
{{- end -}}
{{- if .Values.service.additionalHosts_external }}
{{- range $host := .Values.service.additionalHosts_external }}
  - host: {{ $host }}
    http:
      <<: *httpRule
{{- end -}}
{{- end -}}
{{- end -}}
