import {isPlainObject, isString} from '../utils/predicates.js';

/** Definition of a JoinMap object */
export type JoinMap = Record<string, JoinMap[]>;

/** Definition of a QueryMap object */
export type QueryMap = Record<string, QueryMap[]>;

export type NodeFilterMapKey = 'and' | 'or';

export type NodeFilterMap = Record<NodeFilterMapKey, JSONQueryField[]> & QueryMap;


/** Fields of a FilterNode */
export type JSONQueryField = {
  field_name: string;
  operator: string;
  field_value: string | number | Object;
  field_func?: Object;
}

/**
 * Object definition of JSON query generated by builder
 */
export interface JSONQuery {
  operation: string;
  result_query: {
    join: JoinMap[];
    fields: Record<string, string>;
  };
  queries: QueryMap;
};

/**
 * Validates that data type is a JoinMap object
 * @param x unknown data type
 * @returns boolean
 */
export function isJoinMap(x: unknown): x is Record<string, JoinMap[]> {
  return (
    isPlainObject(x) &&
    Object.keys(x).every(v => isString(v))
  );
}

/**
 * Validates that data type is a QueryMap object
 * @param x unknown data type
 * @returns boolean
 */
export function isQueryMap(x: unknown): x is Record<string, QueryMap[]> {
  return (
    isPlainObject(x) &&
    Object.keys(x).every(v => isString(v))
  );
}

/**
 * Validates fields of JSONQuery object
 * @param data unknown data type
 * @returns boolean
 */
export function isJSONQuery(data: unknown): data is JSONQuery {

  /** Ensure data is of object type */
  if (!isPlainObject(data)) return false;

  /** Ensure operation, queries and result_query fields are definied at root of object */
  if (!('operation' in data) || !('queries' in data) || !('result_query' in data)) return false;

  /** operation field (e.g. base_query+audience_n..) is always a string field */
  if (!isString(data.operation)) return false;

  /** queries field is a QueryMap object */
  if (!isQueryMap(data.queries)) return false;

  /** result_query is an object field */
  if (!isPlainObject(data.result_query)) return false;

  /** Ensure join and fields field in result_query */
  if (!('join' in data.result_query) || !('fields' in data.result_query)) return false;

  /** join field within result_query has to be a JoinMap object */
  if (!isJoinMap(data.result_query.join)) return false;

  return true;
}

